# Generated by Django 3.0.4 on 2020-03-29 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('escolha', models.CharField(choices=[('1', 'unidade'), ('2', 'pacote'), ('3', 'peso'), ('4', 'litro')], max_length=100, verbose_name='Precificado por: ')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor do produto')),
                ('quantidade', models.IntegerField(blank=True, default=1, verbose_name='quantidade')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='peso em KG')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='volume em Litro')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('lote', models.CharField(blank=True, default='404', max_length=100, verbose_name='lote')),
                ('tag', models.CharField(blank=True, default='outros', max_length=100, verbose_name='tag onde sera usado o produto EX: lanche, prato')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('dataCompra', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra: ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
